### ISSUE TITLE
Selector needs to be 'lightbox' for swipe to work

### ISSUE THREAD

**Issue by jarimbi** [willwood/topbox#1]
If you use any other selector than 'lightbox' the swiping on touch devices does not work.

**Comment by AlexanderKoe** [comment]
Hi :) I found your plugin today and was happy to use it in my project. I made a small improvement what may add a good usability advantage with only a few lines. I added "afterConstructLightbox" as a new hook, what gives me the ability to make changes to the created html (like "templating features", add more html, change buttons etc...)

init...
`      afterConstructLightbox: function() {},`

after...
`      e.preventDefault();`
`      this.options.beforeShowLightbox.call(this);`
`      var lightbox = this.constructLightbox();`
just this line:
`      this.options.afterConstructLightbox.call(this);`


Thanks for your work,
Alex

**Comment by willwood** [comment]
@AlexanderKoe Brilliant work, many thanks! I'll look at getting this added soon. Still trying to chase a few YouTube bugs currently, due to new attributes they are adding on links. Thank you for your time and code suggestion. Much appreciated.

**Comment by AlexanderKoe** [comment]
happy to help :) 
sorry I just noticed I put this comment into an existing issue...

This is a short example how to use it.
Important: remove the overlay before open a new Lightbox. 

```
[...]
	beforeShowLightbox: function () {
		$('.topbox_overlay').remove(); // need this to reinitialise the changes
	},
	afterConstructLightbox: function () {
		changeTemplate();
	},

[...]

	function changeTemplate() {
		$('.topbox_title_wrap').addClass('text-white text-left');
		$('.topbox_nav').append('<i class="icon-arrow"></i>');
		$('.topbox_close').append('<i class="icon-close"></i>');
	}

```
